# Generated by Django 3.1.14 on 2023-06-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20230627_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='pockemonentity',
            name='armour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pockemonentity',
            name='damage',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='pockemonentity',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pockemonentity',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pockemonentity',
            name='stamina',
            field=models.IntegerField(default=20),
        ),
    ]
