# Generated by Django 3.1.14 on 2023-06-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pockemon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pockemon',
            name='title_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pockemon',
            name='title_jp',
            field=models.TextField(blank=True),
        ),
    ]
