# Generated by Django 3.1.14 on 2023-06-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20230627_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pockemon',
            new_name='Pokemon',
        ),
        migrations.RenameModel(
            old_name='PockemonEntity',
            new_name='PokemonEntity',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pockemon',
            new_name='pokemon',
        ),
    ]
